name: ChairShop CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ChairShop.csproj

      - name: Build
        run: dotnet build ChairShop.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ChairShop.csproj -c Release -o publish

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: publish

  build-angular:
    runs-on: ubuntu-latest
    needs: build-dotnet

    defaults:
      run:
        working-directory: chairshopUI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Authenticate to Azure Artifacts
        run: |
          echo "registry=https://pkgs.dev.azure.com/YashGohil/EmailToolkit/_packaging/email-toolkit-feed/npm/registry/" > ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          echo "//pkgs.dev.azure.com/YashGohil/EmailToolkit/_packaging/email-toolkit-feed/npm/registry/:username=AzureDevOps" >> ~/.npmrc
          echo "//pkgs.dev.azure.com/YashGohil/EmailToolkit/_packaging/email-toolkit-feed/npm/registry/:_password=$(echo -n ${{ secrets.AZURE_NPM_TOKEN }} | base64)" >> ~/.npmrc
          echo "//pkgs.dev.azure.com/YashGohil/EmailToolkit/_packaging/email-toolkit-feed/npm/registry/:email=devops@local" >> ~/.npmrc

      - name: Install Dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Upload Angular Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: chairshopUI/dist
